### ISSUE TITLE
replug_facetime doesn't detect old camera type named "Built-in iSight"

### ISSUE THREAD

**Issue by Nklya** [dskr99/mac_usb_eject#1]
Hello.

Thanks for your tool!

Unfortunately, I faced a problem that `replug_facetime` didn't detect old camera type named "Built-in iSight" in my MacBook Pro Mid 2009.

I changed a pattern in file `replug_facetime.cpp`, line 116 to `if (NULL != strstr(sFriendlyName, "Built-in iSight")) {` and it worked for me after rebuilding.

I can make a Pull request with something like `if (NULL != strstr(sFriendlyName, "FaceTime") || NULL != strstr(sFriendlyName, "Built-in iSight")) {` if you will merge it.

P.S. If someone would repeat that, you need to remove `/bin/replug_facetime` before running make in `replug_facetime` directory.

**Comment by GregMichaelScott** [comment]
I have the same problem, but I don't know how to rebuild. Would you be able to send me your rebuilt file?
